Added hash interface
hyperledger-labs/crypto-lib pull request #13
Opened 2018-10-17 17:31 UTC by mikelodder7

Added hash interface and a few misc fixes

2018-10-24 23:07 UTC, dcmiddle requested changes

2018-10-24 23:07 UTC, dcmiddle commented on libhl-crypto/Cargo.toml
> +blake2b_simd = "0.3.1"
This library looks pretty slick but I think we need to establish some criteria for new libraries. Probably too extensive for PR comment so I'll take it to the list. Initial reservations here though include that it has a single developer and only a few months of activity.

2018-10-24 23:08 UTC, dcmiddle commented on libhl-crypto/src/hash/blake2.rs
> -//}
Probably better if you can squish this into the commit that introduces the file.

2018-10-24 23:55 UTC, mikelodder7 commented
It’s the library that the blake2 authors support

2018-10-25 02:34 UTC, vaporos approved these changes

2018-10-29 15:40 UTC, mikelodder7 commented on libhl-crypto/Cargo.toml
> +blake2b_simd = "0.3.1"
t’s the library that the blake2 authors support

2018-10-31 16:38 UTC, dcmiddle commented on libhl-crypto/Cargo.toml
> +blake2b_simd = "0.3.1"
Per lab discussion the full definition of tiers and review criteria will be formalized as the project launches. Meanwhile no reason to hold up this PR. We will likely have to refactor this blake2 implementation (or any other) into the right tier once we define what 'tier' means in terms of code, namespace, etc.

2018-10-31 17:17 UTC, dcmiddle approved these changes

2018-10-31 17:17 UTC, merged